module.exports = {
	"GET /~node/actions": "$node.actions",
	"GET /~node/options": "$node.options",
	"GET /~node/services": "$node.services",
	"GET /~node/list": "$node.list",

	//Auth apis
	"POST /auth/login": "auth.login",

	//PDF Forms apis
	"POST /pdf-forms/edit-pdf-file": "pdfForms.editPdf",
	"POST /pdf-forms/validate-pass/:token": "pdfForms.validatePassWord",
	"GET /pdf-forms/user-fields/:token": "pdfForms.getUserFields",
	"POST /pdf-forms/validate-form-token/:token": "pdfForms.validateFormToken",
	"POST /pdf-forms/fill-pdf-form": "pdfForms.fillFormFields",
	"POST /pdf-forms/fill-pdf-form-sign": "pdfForms.fillFormFields",
	"GET /pdf-forms/submissions-file": "pdfForms.getAllSubmissions",
	"POST /pdf-forms/submission-reminder": "pdfForms.sendEmailReminder",
	"GET /pdf-forms/expiration": "pdfForms.checkExpiration",
	"GET /pdf-forms/files": "pdfForms.getAllFiles",
	"POST /pdf-forms/upload": "pdfForms.uploadPdfFile",
	"DELETE /pdf-forms/destroy/:id": "pdfForms.deleteFile",
	"POST /pdf-forms/check-duplicate": "pdfForms.checkDuplicateFile",
	"POST /pdf-forms/void": "pdfForms.voidForm",
	"GET /pdf-forms/:id/type/:mode": "pdfForms.getAllFields",
	"DELETE /pdf-forms/:id": "pdfForms.deleteForm",
	"POST /pdf-forms/resend": "pdfForms.resendEmails",
	"GET /pdf-forms/activity-history/:id": "pdfForms.activityHistory",
	"POST /pdf-forms/delete-file-s3": "pdfForms.deleteFileFromS3",
	"POST /pdf-forms/save-to-template": "pdfForms.saveToTemplate",
	"POST /pdf-forms/check-template-exists": "pdfForms.checkIfTemplateExists",
	"POST /pdf-forms/verify-token": "pdfForms.verifyPDFToken",
	"POST /pdf-forms/add-tags": "pdfForms.addFormTags",
	"GET /pdf-forms/tags": "pdfForms.getAllTags",
	"POST /pdf-forms/decline": "pdfForms.declineForm",
	"POST /pdf-forms/update-recipient-mail-status":
		"pdfForms.updateRecipientStatus",
	"POST /pdf-forms/send-reminder": "pdfForms.sendReminderToRecipients",
	"POST /pdf-forms/heart-beat": "documents.heartBeat",
	"POST /pdf-forms/extend-expiration": "pdfForms.extendExpirationDate",
	"POST /pdf-forms/verify-expiration-token":
		"pdfForms.extendExpirationDateByToken",
	"GET /pdf-forms/signature/:id/:email": "pdfForms.getUserSignature",
	"POST /pdf-forms/self-sign": "pdfForms.selfSignForm",
	// "POST /addAuditLog": "pdfForms.addAuditLog",
};
